select * from reservation;
select * from order_info;
select * from item;
select * from customer;
select * from address;

-- M0001 Special_set 온라인_전용상품 combo 24000

-- Q2
select count(*)as 총주문건, sum(sales)as 총매출합계, round(avg(sales)) 평균매출 , max(sales) 최고매출, min(sales) 최저매출
from order_info;

-- Q3
SELECT B.CNT 총주문건수 , B.SS 총매출합계 , A.CNT 전용상품주문건수, A.SS 전용상품매출합계, ROUND(A.CNT/B.CNT*100,2) 주문건수비율, ROUND(A.SS/B.SS*100,2) 매출합계비율
FROM(
SELECT ITEM_ID, COUNT(ORDER_NO) CNT, SUM(SALES) SS
FROM ORDER_INFO
WHERE ITEM_ID = 'M0001'
GROUP BY ITEM_ID)
A JOIN(SELECT ITEM_ID, COUNT(ORDER_NO) CNT, SUM(SALES) SS
    FROM ORDER_INFO
) B
ON 1=1;

-- Q4
/*
SELECT A.ITEM_ID, B.PRODUCT_NAME, SUM(A.SALES)
FROM ORDER_INFO A JOIN ITEM B ON A.ITEM_ID = B.ITEM_ID
GROUP BY A.ITEM_ID;
*/


SELECT A.ITEM_ID, B.PRODUCT_NAME, A.매출합계
FROM ITEM B JOIN (
SELECT ITEM_ID, SUM(SALES) 매출합계
FROM ORDER_INFO
GROUP BY ITEM_ID) A
ON B.ITEM_ID = A.ITEM_ID
ORDER BY A.매출합계 DESC;

-- Q5
/*
SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)),
(SELECT SUM(SALES) FROM ORDER_INFO WHERE ITEM_ID='M0001' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) SPECIAL_SET
FROM ORDER_INFO
GROUP BY CONCAT(20,SUBSTR(ORDER_NO,1,4))
ORDER BY CONCAT(20,SUBSTR(ORDER_NO,1,4));
*/


SELECT A.DAT 년월, A.S SPECIAL_SET, B.S PASTA, NVL(C.S,0) PIZZA, NVL(D.S,0) SEA_FOOD, NVL(E.S,0) STEAK, NVL(F.S,0) SALAD_BAR, NVL(G.S,0) SALAD, H.S SANDWICH, NVL(I.S,0) WINE, NVL(J.S,0) JUICE
FROM
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0001' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) A
LEFT JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0002' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) B
ON A.DAT=B.DAT
LEFT JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0003' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) C
ON A.DAT=C.DAT
LEFT JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0004' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) D
ON A.DAT=D.DAT
LEFT JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0005' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) E
ON A.DAT=E.DAT
LEFT JOIN(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0006' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) F
ON A.DAT=F.DAT
LEFT JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0007' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) G
ON A.DAT=G.DAT
LEFT JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0008' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) H
ON A.DAT=H.DAT
LEFT JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0009' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) I
ON A.DAT = I.DAT
LEFT JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0010' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) J
ON A.DAT = J.DAT
ORDER BY 년월;

-- Q6
SELECT A.DAT 년월, B.S 매출합계, A.S SPECIAL_SET
FROM
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0001' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) A
JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) B
ON A.DAT = B.DAT;

-- Q7
SELECT A.DAT 년월, B.S-A.S ETC, A.S SPECIAL_SET, ROUND(A.S/B.S*100,1) 매출기여율
FROM
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0001' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) A
JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) B
ON A.DAT = B.DAT;

-- Q8
SELECT A.DAT 년월, B.S-A.S ETC, A.S SPECIAL_SET, ROUND(A.S/B.S*100,1) 매출기여율, B.C+C.CNT 총주문건, B.C 예약완료건, C.CNT 예약취소건
FROM
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0001' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) A
JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S, COUNT(RESERV_NO) C FROM ORDER_INFO GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) B
ON A.DAT = B.DAT
JOIN
(SELECT SUBSTR(RESERV_NO,1,6) DAT, COUNT(RESERV_NO) CNT FROM RESERVATION WHERE CANCEL='Y' GROUP BY SUBSTR(RESERV_NO, 1,6) ORDER BY SUBSTR(RESERV_NO, 1,6)) C
ON A.DAT = C.DAT;

-- Q9
SELECT A.DAT 년월, B.C+C.CNT 총주문건, B.C 예약완료건, C.CNT 예약취소건, CONCAT(ROUND(C.CNT/(B.C+C.CNT)*100,1),'%') 예약취소율
FROM
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0001' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) A
JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S, COUNT(RESERV_NO) C FROM ORDER_INFO GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) B
ON A.DAT = B.DAT
JOIN
(SELECT SUBSTR(RESERV_NO,1,6) DAT, COUNT(RESERV_NO) CNT FROM RESERVATION WHERE CANCEL='Y' GROUP BY SUBSTR(RESERV_NO, 1,6) ORDER BY SUBSTR(RESERV_NO, 1,6)) C
ON A.DAT = C.DAT;

-- Q10
WITH A AS (
SELECT ITEM_ID, SALES, SUBSTR(RESERV_NO,1,6) 연월, TO_CHAR(TO_DATE(SUBSTR(RESERV_NO,1,8),'YYYYMMDD'), 'DAY') 요일
FROM ORDER_INFO
WHERE ITEM_ID ='M0001')
SELECT 연월,
    SUM(CASE WHEN A.요일 = '일요일' THEN SALES ELSE 0 END) 일요일,
    SUM(CASE WHEN A.요일 = '월요일' THEN SALES ELSE 0 END) 월요일,
    SUM(CASE WHEN A.요일 = '화요일' THEN SALES ELSE 0 END) 화요일,
    SUM(CASE WHEN A.요일 = '수요일' THEN SALES ELSE 0 END) 수요일,
    SUM(CASE WHEN A.요일 = '목요일' THEN SALES ELSE 0 END) 목요일,
    SUM(CASE WHEN A.요일 = '금요일' THEN SALES ELSE 0 END) 금요일,
    SUM(CASE WHEN A.요일 = '토요일' THEN SALES ELSE 0 END) 토요일
FROM A
GROUP BY 연월
ORDER BY 연월;
-- SUM()안에 CASE를 IF처럼 사용하기 --> CASE WHEN 조건 THEN 참결과 ELSE 거짓결과 (IF문처럼 유용하게 사용 가능)
-- Q11
SELECT *
FROM
(SELECT
SUBSTR(A.RESERV_NO, 1, 6) 년월, B.BRANCH 지점, SUM(A.SALES) 매출액, RANK() OVER(PARTITION BY SUBSTR(A.RESERV_NO, 1, 6) ORDER BY SUM(A.SALES) DESC) AS 순위
FROM ORDER_INFO A JOIN RESERVATION B ON A.RESERV_NO = B.RESERV_NO
WHERE A.ITEM_ID = 'M0001'
GROUP BY B.BRANCH, SUBSTR(A.RESERV_NO, 1, 6)
) SUBQ
WHERE SUBQ.순위<=3
ORDER BY SUBQ.년월, SUBQ.지점 DESC, 순위;


SELECT *
FROM(
SELECT SUBQ.년월, SUBQ.지점, SUBQ.매출액, RANK() OVER(PARTITION BY SUBQ.년월 ORDER BY SUBQ.지점 DESC) 순위
FROM
(SELECT
SUBSTR(A.RESERV_NO, 1, 6) 년월, B.BRANCH 지점, SUM(A.SALES) 매출액, RANK() OVER(PARTITION BY SUBSTR(A.RESERV_NO, 1, 6) ORDER BY SUM(A.SALES) DESC) AS 순위
FROM ORDER_INFO A JOIN RESERVATION B ON A.RESERV_NO = B.RESERV_NO
WHERE A.ITEM_ID = 'M0001'
GROUP BY B.BRANCH, SUBSTR(A.RESERV_NO, 1, 6)
) SUBQ
WHERE SUBQ.순위=1
ORDER BY SUBQ.년월, SUBQ.지점 DESC, 순위) SUBQQ
WHERE SUBQQ.순위=1;
-- ROW_NUMBER() 쓰면 한 번에 끝냈을 거 같음

SELECT *
FROM
(SELECT
SUBSTR(A.RESERV_NO, 1, 6) 년월, B.BRANCH 지점, SUM(A.SALES) 매출액, ROW_NUMBER() OVER(PARTITION BY SUBSTR(A.RESERV_NO, 1, 6) ORDER BY SUM(A.SALES) DESC, B.BRANCH DESC) AS 순위
FROM ORDER_INFO A JOIN RESERVATION B ON A.RESERV_NO = B.RESERV_NO
WHERE A.ITEM_ID = 'M0001'
GROUP BY B.BRANCH, SUBSTR(A.RESERV_NO, 1, 6)
) SUBQ
WHERE SUBQ.순위<=1
ORDER BY SUBQ.년월, SUBQ.지점 DESC, 순위;
-- ROW_NUMBER()로 한 번에 끝내기

-- Q12
WITH A AS
(SELECT A.DAT 년월, B.S 총매출, B.S-A.S 전용상품외매출, A.S 전용상품매출, ROUND(A.S/B.S*100,1) 전용상품판매율
FROM
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0001' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) A
JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S, COUNT(RESERV_NO) C FROM ORDER_INFO GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) B
ON A.DAT = B.DAT
JOIN
(SELECT SUBSTR(RESERV_NO,1,6) DAT, COUNT(RESERV_NO) CNT FROM RESERVATION WHERE CANCEL='Y' GROUP BY SUBSTR(RESERV_NO, 1,6) ORDER BY SUBSTR(RESERV_NO, 1,6)) C
ON A.DAT = C.DAT),
B AS
(SELECT A.DAT 년월, B.C+C.CNT 총주문건, B.C 예약완료건, C.CNT 예약취소건, CONCAT(ROUND(C.CNT/(B.C+C.CNT)*100,1),'%') 예약취소율
FROM
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S FROM ORDER_INFO WHERE ITEM_ID='M0001' GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) A
JOIN
(SELECT CONCAT(20,SUBSTR(ORDER_NO,1,4)) DAT, SUM(SALES) S, COUNT(RESERV_NO) C FROM ORDER_INFO GROUP BY SUBSTR(ORDER_NO, 1,4) ORDER BY SUBSTR(ORDER_NO, 1,4)) B
ON A.DAT = B.DAT
JOIN
(SELECT SUBSTR(RESERV_NO,1,6) DAT, COUNT(RESERV_NO) CNT FROM RESERVATION WHERE CANCEL='Y' GROUP BY SUBSTR(RESERV_NO, 1,6) ORDER BY SUBSTR(RESERV_NO, 1,6)) C
ON A.DAT = C.DAT),
C AS
(SELECT *
FROM(
SELECT SUBQ.년월, SUBQ.지점, SUBQ.매출액, RANK() OVER(PARTITION BY SUBQ.년월 ORDER BY SUBQ.지점 DESC) 순위
FROM
(SELECT
SUBSTR(A.RESERV_NO, 1, 6) 년월, B.BRANCH 지점, SUM(A.SALES) 매출액, RANK() OVER(PARTITION BY SUBSTR(A.RESERV_NO, 1, 6) ORDER BY SUM(A.SALES) DESC) AS 순위
FROM ORDER_INFO A JOIN RESERVATION B ON A.RESERV_NO = B.RESERV_NO
WHERE A.ITEM_ID = 'M0001'
GROUP BY B.BRANCH, SUBSTR(A.RESERV_NO, 1, 6)
) SUBQ
WHERE SUBQ.순위=1
ORDER BY SUBQ.년월, SUBQ.지점 DESC, 순위) SUBQQ
WHERE SUBQQ.순위=1)
SELECT A.년월 AS 매출월, A.총매출, A.전용상품외매출, A.전용상품판매율, B.예약완료건, B.예약취소건, B.예약취소율, C.지점 최대매출지점, C.매출액 지점매출액
FROM A JOIN B ON A.년월=B.년월 JOIN C ON A.년월 = C.년월;


-- Q13
SELECT COUNT(*)
    고객수,
    SUM(CASE WHEN SEX_CODE = 'M' THEN 1 ELSE 0 END) 남자,
    SUM(CASE WHEN SEX_CODE = 'F' THEN 1 ELSE 0 END) 여자,
    ROUND(AVG(EXTRACT(YEAR FROM SYSDATE)-SUBSTR(BIRTH,1,4)),1) 평균나이
FROM CUSTOMER;

-- Q14
SELECT B.CUSTOMER_ID 고객ID, C.CUSTOMER_NAME 고객명, COUNT(A.RESERV_NO) 전체상품주문건수, SUM(SALES) 총매출,
COUNT(CASE WHEN A.ITEM_ID='M0001' THEN 1 ELSE NULL END) 전용상품주문건수,
SUM(CASE WHEN A.ITEM_ID='M0001' THEN SALES ELSE 0 END) 전용상품매출
FROM ORDER_INFO A JOIN RESERVATION B
ON A.RESERV_NO = B.RESERV_NO
JOIN CUSTOMER C
ON B.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY B.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY 전용상품매출 DESC;

-- Q15
SELECT A.CUSTOMER_ID 고객ID, CUSTOMER_NAME 고객명, SUM(B.SALES) 전용상품매출, ROW_NUMBER() OVER(ORDER BY SUM(B.SALES) DESC) 순위
FROM RESERVATION A JOIN ORDER_INFO B
ON A.RESERV_NO = B.RESERV_NO
JOIN CUSTOMER C
ON A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE B.ITEM_ID = 'M0001'
GROUP BY A.CUSTOMER_ID, CUSTOMER_NAME;

-- 오래걸린 Q3 다시해보기
WITH A AS(
SELECT COUNT(*) 총주문건수, SUM(SALES) 총매출합계
FROM ORDER_INFO),
B AS(
SELECT COUNT(*) 전용상품주문수, SUM(SALES) 전용상품매출합계
FROM ORDER_INFO
WHERE ITEM_ID = 'M0001')
SELECT A.총주문건수, A.총매출합계, B.전용상품주문수, B.전용상품매출합계, 
ROUND(B.전용상품주문수/A.총주문건수*100,2)주문건수비율,
ROUND(B.전용상품매출합계/A.총매출합계*100,2)매출합계비율
FROM A JOIN B ON 1=1;
-- CASE문 활용
SELECT A.총주문건수, A.총매출합계, A.전용상품주문수, A.전용상품매출합계, 
ROUND(A.전용상품주문수/A.총주문건수*100,2) 주문건수비율,
ROUND(A.전용상품매출합계/A.총매출합계*100,2) 매출합계비율
FROM(
SELECT COUNT(*) 총주문건수, SUM(SALES) 총매출합계,
SUM(CASE WHEN ITEM_ID = 'M0001' THEN 1 ELSE 0 END) 전용상품주문수,
SUM(CASE WHEN ITEM_ID = 'M0001' THEN SALES ELSE 0 END) 전용상품매출합계
FROM ORDER_INFO) A;

-- Q5 시계열분석 다시해보기
SELECT
SUBSTR(RESERV_NO,1,6) 년월,
SUM(CASE WHEN ITEM_ID = 'M0001' THEN SALES ELSE 0 END) SPECIAL_SET,
SUM(CASE WHEN ITEM_ID = 'M0002' THEN SALES ELSE 0 END) PASTA,
SUM(CASE WHEN ITEM_ID = 'M0003' THEN SALES ELSE 0 END) PIZZA,
SUM(CASE WHEN ITEM_ID = 'M0004' THEN SALES ELSE 0 END) SEA_FOOD,
SUM(CASE WHEN ITEM_ID = 'M0005' THEN SALES ELSE 0 END) STEAK,
SUM(CASE WHEN ITEM_ID = 'M0006' THEN SALES ELSE 0 END) SALAD_BAR,
SUM(CASE WHEN ITEM_ID = 'M0007' THEN SALES ELSE 0 END) SALAD,
SUM(CASE WHEN ITEM_ID = 'M0008' THEN SALES ELSE 0 END) SANDWITCH,
SUM(CASE WHEN ITEM_ID = 'M0009' THEN SALES ELSE 0 END) WINE,
SUM(CASE WHEN ITEM_ID = 'M0010' THEN SALES ELSE 0 END) JUICE
FROM ORDER_INFO
GROUP BY SUBSTR(RESERV_NO,1,6)
ORDER BY 년월;

-- 졸업 굿